version: '3'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    environment:
      JWT_SECRET: i12je23r3rik
      NODE_ENV: development
      MONGO_URL: mongodb://mongo:27017/bloodbank
    depends_on:
      - mongo
    networks:
      - mern-network

  frontend:
    build: ./client
    ports:
      - "3000:80"  # Change to serve through port 80 for Nginx
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client/src:/usr/src/app/src  # Optional: bind frontend source for hot-reloading
    environment:
      - REACT_APP_BASEURL=http://host.docker.internal:8080/api/v1
    networks:
      - mern-network

  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
